# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "2i2c Hubs"
  url = "infrastructure/"
  weight = 10

[[main]]
  name = "Open Source"
  url = "open-source/"
  weight = 20

[[main]]
  name = "About Us"
  identifier = "about"
  weight = 30

  [[main]]
  parent = "about"
  name = "About 2i2c"
  url = "about/"
  weight = 10

  [[main]]
  parent = "about"
  name = "Founding Team"
  url = "founders/"
  weight = 10

  [[main]]
  parent = "about"
  name = "Get Involved"
  url = "about#getinvolved"
  weight = 10

[[main]]
  name = "Blog"
  url = "posts/"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

